# -*- coding: utf-8 -*-
"""LR_Cleveland_Final

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m5U0ArGJrI7L1F1ciGI0KzCKMRos-cub
"""

import pandas as pd

df = pd.read_excel('/content/drive/MyDrive/Final Project/Final Project/Dataset/Cleveland Dataset (1).xlsx')

df

df['num']=df['num'].map({0:0,1:1,2:1,3:1,4:1})

df

df.shape

df=  df.dropna(inplace=False)

df

# splitting into input and output datasets
X= df.iloc[:,:-1] # all columns except the last one
y=df.iloc[:,-1]# just the last column

X

y

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.33, random_state=42)

from sklearn.linear_model import LogisticRegression
classifier= LogisticRegression(penalty='l2',C=1,max_iter=100)
from sklearn.model_selection import GridSearchCV
parameter={'penalty':['l1','l2','elacticnet'],'C':[1,2,3,4,5,6,10,20,30,40,50],'max_iter':[100,200,300]}
classifier_regressor=GridSearchCV(classifier,param_grid=parameter,scoring='accuracy',cv=5)
classifier_regressor.fit(X_train,y_train)

print(classifier_regressor.best_params_)

from sklearn.metrics import accuracy_score,classification_report

y_pred= classifier_regressor.predict(X_test)

score= accuracy_score(y_pred,y_test)
print(score)

from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))